# Generated by Django 3.1.1 on 2020-09-30 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Device',
        ),
    ]
