# Generated by Django 3.1.1 on 2020-09-30 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200930_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_results',
            old_name='test_Sequence',
            new_name='test_sequence',
        ),
    ]
