# Generated by Django 3.1.1 on 2020-10-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200930_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='model',
            new_name='model_number',
        ),
    ]
