# Generated by Django 3.1.1 on 2020-11-11 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Performance_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=200)),
                ('sequence_ID', models.CharField(max_length=200)),
                ('max_system_voltage', models.CharField(max_length=200)),
                ('voc', models.CharField(max_length=200)),
                ('isc', models.CharField(max_length=200)),
                ('vmp', models.CharField(max_length=200)),
                ('imp', models.CharField(max_length=200)),
                ('pmp', models.CharField(max_length=200)),
                ('ff', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('cell_technology', models.CharField(max_length=200)),
                ('cell_manufacturer', models.CharField(max_length=200)),
                ('num_of_cells', models.IntegerField(default=0)),
                ('num_of_cells_in_series', models.IntegerField(default=0)),
                ('num_of_series_strings', models.IntegerField(default=0)),
                ('num_of_diodes', models.IntegerField(default=0)),
                ('product_length', models.CharField(max_length=200)),
                ('product_width', models.CharField(max_length=200)),
                ('superstate_manufacturer', models.CharField(max_length=200)),
                ('substrate_type', models.CharField(max_length=200)),
                ('substrate_manufacturer', models.CharField(max_length=200)),
                ('frame_type', models.CharField(max_length=200)),
                ('frame_adhesive', models.CharField(max_length=200)),
                ('encapsulate_type', models.CharField(max_length=200)),
                ('encapsulate_manufacturer', models.CharField(max_length=200)),
                ('junction_box_type', models.CharField(max_length=200)),
                ('junction_box_manufacturer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('m_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('office_phone', models.CharField(max_length=50)),
                ('cell_phone', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=50)),
                ('client_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('is_FI_required', models.CharField(max_length=50)),
                ('FI_freqeuncy', models.CharField(max_length=50)),
                ('standard_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.test_standard')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=50)),
                ('address_2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('fax_number', models.CharField(max_length=50)),
                ('client_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.client')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_id', models.CharField(max_length=50)),
                ('report_number', models.CharField(max_length=50)),
                ('issue_date', models.CharField(max_length=50)),
                ('location_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.location')),
                ('model_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
                ('standard_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.test_standard')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
